    <!--Let us uncoment Hero Home and also it's partials until we are done fixing it by doing the intersction Observation and also independent classing-->
    
     <!-- Home Hero Carousel Start -->
    <div id="home-hero" class="homeHero-carousel carousel-window home-hero">

        <div class="carousel-indicator">
        <!-- dots will be generated by JS -->
        </div>

        <div class="carousel-wrapper homeHero">
            <div class="slide" data-bg="3">
                <div class="textInfo-wrapper">
                    <p class="label-h1">OUR SERVICE</p>
                        <!--Label can be empty and the height wil still be maintined ALSO you can include the height as well-->
                
                    <h1 class="heading title display">Payment Processing</h1>
                    <p class="display subtitle">Our solutions are designed to meet unique needs.</p>
                        
                    <div class="cta-container-hero">
                        <button class="btn-primary" onclick="window.location.href='<?= $base_url ?>/merchant-application'">Apply Now</button>
                        <button class="btn-secondary" onclick="window.location.href='<?= $base_url ?>/processing-solutions'">Learn More</button>
                    </div>                     
                </div>
                <div class="image-wrapper">
                    <img src="<?= $base_url ?>/assets/images/hero/paymentProcessing_HeroMobile.webp" alt="PaymentProcessing" width="300px" height="250px" fetchpriority="high">
                </div>             
            </div>                

            <div class="slide" data-bg="4">
                <div class="textInfo-wrapper">
                    <p class="label-h1">BECOME A MERCHANT</p>
                    <!--Label can be empty and the height wil still be maintined ALSO you can include the height as well-->
                
                    <h1 class="heading title display">Merchant Application</h1>
                    <p class="display subtitle">Start accepting payments with confidence.</p>
                     
                    <div style="display:flex;" class="cta-container-hero">
                        <button style="width:200px;" class="btn-primary" onclick="window.location.href='<?= $base_url ?>/merchant-application'">Fill The Form</button>
                        <button style="display:none;" class="btn-secondary" onclick="window.location.href='<?= $base_url ?>/merchant-application'">Learn More</button>
                    </div> 
                </div>
                <div class="image-wrapper">
                    <img src="<?= $base_url ?>/assets/images/hero/Merchant-Application--FillForm-Optimum.webp" alt="MerchantApplication" width="300px" height="250px" fetchpriority="high">
                </div>            
            </div>

            <div class="slide" data-bg="2">
                <div class="textInfo-wrapper">
                    <p class="label-h1">ROK</p>
                    
                    <h1 class="heading title display">Business Financing</h1>
                    <p class="display subtitle">Get the funding your business deserves today.</p>
                    
                    <div class="cta-container-hero">
                        <!-- Takes us to our partners main page through our referral - external  link -->
                        <button class="btn-primary" onclick="window.open('https://go.mypartner.io/business-financing/?ref=0014x00000KOZXNAA5', '_blank')">Get Started</button>

                        <!-- Takes us to our own webpage with our partner collab page internal  link -->
                        <button class="btn-secondary" onclick="window.location.href='<?= $base_url ?>/business-financing'">Learn More</button>
                    </div>
                </div>
                <div class="image-wrapper">
                        <img src="<?= $base_url ?>/assets/images/hero/businessFinancing-rok-financial_mobileHomeHero.webp" alt="BusinessFinancing" width="300px" height="250px" fetchpriority="high">
                </div>            
            </div>  

            <div class="slide" data-bg="5">
                <div class="textInfo-wrapper">
                    <p class="label-h1">Just For You</p>
                    <h1 style="color:#333;" class="heading title display">Digital <br class="mobile-break-homeHeroText"> Services</h1>
                    <p  style="color:#1f1d1d;" class="display subtitle">Let's help you realize your imagination.</p>  

                    <div class="cta-container-hero">
                        <button class="btn-primary" onclick="window.location.href='<?= $base_url ?>/digital-services-brief-submit'">Post a Brief</button>
                        <button class="btn-secondary digital-creative" onclick="window.location.href='<?= $base_url ?>/digital-services'">Learn More</button>
                    </div>  
                </div> 

                <div class="image-wrapper">
                    <img src="<?= $base_url ?>/assets/images/hero/DigitalService--mobile-HomeHero.webp" alt="DigitalServices" width="300px" height="250px" fetchpriority="high">
                </div>  
            </div>

            <div class="slide" data-bg="1">
                <div class="textInfo-wrapper">
                    <!--Label can be empty and the height wil still be maintined ALSO you can include the height as well-->
                    <p  class="label-h1">SOLUTIONS PROVIDER</p>
                    <h1 style="color:var(--blue-500)" class="heading title display">Optimum Payments</h1>
                    <p style="color:#1f1d1d;" class="display subtitle">A full provider of payment processing and business financing.</p> 
                    
                    <div class="cta-container-hero">
                        <button class="btn-primary" onclick="window.location.href='<?= $base_url ?>/micro-services'">View Extra Services</button>
                        <button class="btn-secondary" onclick="window.location.href='<?= $base_url ?>/about'">Learn More</button>
                    </div>
                    </div>
                <div class="image-wrapper">
                    
                    <img src="<?= $base_url ?>/assets/images/hero/optimum-payments-mobileHomeHero.webp" alt="" width="300px" height="250px" fetchpriority="high">
                </div>                
            </div>
        </div>
    </div>
    <!-- Home Hero Carousel End -->

    <!-- </div> -->

    <style>
        button.btn-secondary.digital-creative{
            color:#333;
            border:1px solid #333;
        }

        button.btn-secondary.digital-creative:hover{
            color:#333;
            border:1px solid #686868;
            transition: border 300ms;
        }    


      
    </style>

    <link rel="stylesheet" href="<?= $base_url ?>/assets/css/homeHeroCarousel.css">    
    <script src="<?= $base_url ?>/assets/js/homeHeroCarousel.js" defer></script>